# Generated by Django 3.1.3 on 2020-11-16 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_anywhere', '0002_auto_20201115_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_departure', to='travel_anywhere.airport'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='travel_anywhere.hotel'),
        ),
    ]
